# Generated by Django 4.1.3 on 2023-01-16 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_team_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='twitter_link',
            field=models.URLField(default='', max_length=100),
        ),
    ]
