# Generated by Django 4.1.3 on 2023-01-16 11:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_title', models.CharField(max_length=255)),
                ('state', models.CharField(choices=[('al', 'alabama'), ('ak', 'alaska'), ('wy', 'wyoming'), ('wi', 'wisconsin')], max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.IntegerField(choices=[(2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023)], verbose_name='year')),
                ('condition', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('description', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('car_photo_1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('car_photo3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('car_photo_4', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('features', models.CharField(choices=[('cruise control', 'cruis control'), ('audio interface', 'audio interface'), ('alarm syste', 'malarm system'), ('seat heatin', 'seat heating')], max_length=100)),
                ('body_style', models.CharField(max_length=100)),
                ('engin', models.CharField(max_length=100)),
                ('transmission', models.CharField(max_length=100)),
                ('interior', models.CharField(max_length=100)),
                ('miles', models.IntegerField()),
                ('doors', models.CharField(choices=[('4', '4'), ('5', '5'), ('3', '3'), ('6', '6')], max_length=100)),
                ('passengers', models.IntegerField()),
                ('vin_o', models.CharField(max_length=100)),
                ('milage', models.CharField(max_length=100)),
                ('fuel_type', models.CharField(max_length=100)),
                ('no_of_owners', models.CharField(max_length=100)),
                ('is_feachured', models.BooleanField(max_length=100)),
                ('created_date', models.DateTimeField(blank=True, verbose_name=datetime.datetime.now)),
            ],
        ),
    ]
